name: Lab7 Build Trigger

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run basic script
        run: echo "🚀 Lab 7 build triggered from dashboard"